version: "3.8"
services:
  backend:
    restart: unless-stopped
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - ./certs/certbot/conf:/etc/letsencrypt
      - ./certs/certbot/www:/var/www/certbot
  frontend: # This runs the routing server
    restart: unless-stopped
    build: ./client
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./certs/certbot/conf:/etc/letsencrypt
      - ./certs/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    links:
      - "backend:backend"
  certbot:
    image: certbot/certbot
    volumes: 
      - ./certs/certbot/conf:/etc/letsencrypt
      - ./certs/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  database:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ytt123
      MYSQL_DATABASE: brown_bytes
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: