version: "3.8"
services:
  https-portal1:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - frontend
    restart: always
    environment:
      STAGE: local
      DOMAINS: 'brownbytes.org -> http://frontend:80'
      # STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'
    volumes: 
      - https-portal-data1:/var/lib/https-portal
  https-portal2:
    image: steveltn/https-portal:1
    ports:
      - '8080:80'
      - '8443:443'
    links:
      - backend
    restart: always
    environment:
      STAGE: local
      DOMAINS: 'api.brownbytes.org -> http://backend:8080'
      # STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'
    volumes: 
      - https-portal-data2:/var/lib/https-portal
  backend:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - database
  frontend:
    build: ./client
    # ports:
    #   - "80:80"
    #   - "443:443"
    depends_on:
      - backend
    # volumes:
    #   - ./certs/certbot/conf:/etc/letsencrypt
    #   - ./certs/certbot/www:/var/www/certbot
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  # certbot:
  #   image: certbot/certbot
  #   volumes: 
  #     - ./certs/certbot/conf:/etc/letsencrypt
  #     - ./certs/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  database:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ytt123
      MYSQL_DATABASE: brown_bytes
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
  https-portal-data1:
  https-portal-data2: