version: "3.8"
services:
  database:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ytt123
      MYSQL_DATABASE: brown_bytes
    volumes:
      - my-db:/var/lib/mysql
  backend:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - database
  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  my-db:
