export const SET_ALERT = "SET_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_EMAIL_SENT = "REGISTER_EMAIL_SENT";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_PROFILE = "GET_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";

export const ADD_POST = "ADD_POST";
export const DELETE_POST = "DELETE_POST";
export const POST_ERROR = "POST_ERROR";
export const GET_POST = "GET_POST";
export const GET_POSTS = "GET_POSTS";

export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";

export const GET_EVENTS = "GET_EVENTS";
export const ADD_EVENT = "ADD_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const UPDATE_WATCHES = "UPDATE_WATCHES";
export const ADD_EVENT_ERROR = "ADD_EVENT_ERROR";

export const GET_OFFERS = "GET_OFFERS";
export const CREATE_OFFER_SUCCESS = "CREATE_OFFER_SUCCESS";
export const CREATE_OFFER_FAILED = "CREATE_OFFER_FAILED";
export const DELETE_OFFER = "DELETE_OFFER";
export const CHANGE_QUERY_STRING = "CHANGE_QUERY_STRING";

export const UPDATE_AVATAR_SUCCESS = "UPDATE_AVATAR_SUCCESS";
export const UPDATE_AVATAR_FAILED = "UPDATE_AVATAR_FAILED";
export const UPDATE_SOCIAL_LINKS_SUCCESS = "UPDATE_SOCIAL_LINKS_SUCCESS";
export const UPDATE_SOCIAL_LINKS_FAILED = "UPDATE_SOCIAL_LINKS_FAILED";
